name: core_sdk
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # DATA
  equatable: ^1.2.5 
  fimber: ^0.4.4
  google_maps_flutter: ^0.5.21

  # LOCALIZATION
  # intl: ^0.16.1

  # NETWORKING 
  dio: ^3.0.10
  data_connection_checker: ^0.3.4

  # STATE MANAGMENT
  flutter_bloc: ^6.1.1
  mobx: ^1.2.1+4
  provider: ^4.3.3

  # DI
  get_it: ^5.0.3
  injectable: ^1.0.7

  # LOCATIONS
  location: ^3.0.0

  # UI
  fluttertoast: ^7.1.8
  auto_size_text: ^2.1.0
  flutter_mobx: ^1.1.0+2
  simple_animations: ^1.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.2
  built_value_generator: ^7.1.0
  json_serializable: ^3.2.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
